version: '0.0.{build}'
image: Visual Studio 2019

# Setup environment
nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
    - /tmp|temp/

skip_commits:
  files:
  - .github/
  - .gitattributes
  - .gitignore
  - LICENSE
  - README.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - CODE_OF_CONDUCT.md
  - '**/*.DotSettings'

environment:
  SONARQUBE_TOKEN:
    secure: 3wp08w0E7dvLNXiVvmxU0KaeMvr8sAFNSoiaTGV/yZBND0dgJ18NbFJnwtwe09vM
  DocFXVersion: 2.51
  NUnitConsoleVersion: 3.10.0
  OpenCoverVersion: 4.7.922
  CoverallsVersion: 1.0.0
  COVERALLS_REPO_TOKEN:
    secure: UXj7LMvcwlRWY+UFiqS6Pqbs8vZjZbDaCMYIwk9YPXcOFbDK8io7lH6/1s0D1uOO
  GITHUB_ACCESS_TOKEN:
    secure: fLTTmcGOM55kigJC4vErpObFmybCtzQtwb4QN55BTNq3GDGaOCoHDoIPxexzO59d
  GITHUB_EMAIL:
    secure: wcfqCHOmeRLZf/BX6u6qQSV89Q4jFs9fHNDgMpKAcqE=

# Setup build version
install:
  - ps: ./build/setupBuild.ps1

# Assembly infos & csproj patching
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '$(Build_Assembly_Version)'
  assembly_file_version: '$(Build_Assembly_Version)'
  assembly_informational_version: '$(Build_Version)'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(Build_Assembly_Version)'
  package_version: '$(Build_Version)'
  assembly_version: '$(Build_Assembly_Version)'
  file_version: '$(Build_Assembly_Version)'
  informational_version: '$(Build_Version)'

# Build configurations
platform:
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Build
before_build:
# NuGet restore
  - nuget restore -verbosity detailed
# SonarQube
  - ps: >-
      if ($env:IsFullIntegrationBuild -eq $true)
      {
          dotnet tool install --tool-path tools dotnet-sonarscanner
          $sonarScanner = (Resolve-Path "tools\dotnet-sonarscanner.exe").ToString()
      }

build:
  verbosity: minimal

build_script:
# Start SonarQube analysis (only for Release configuration)
  - ps: $analysisFile = (Convert-Path SonarQube.Analysis.xml).ToString()
  - ps: >-
      if ($env:IsFullIntegrationBuild -eq $true)
      {
          & $sonarScanner begin /k:"graphshape" /s:$analysisFile /o:"kernelith-github" /d:sonar.host.url="https://sonarcloud.io" /d:"sonar.branch.name=$env:APPVEYOR_REPO_BRANCH" /d:sonar.cs.opencover.reportsPaths="coverage.xml" /d:sonar.login="$env:SONARQUBE_TOKEN"
      }
  - msbuild

before_test:
# NuGet packages for test & coverage
  - ps: >-
      nuget install NUnit.Console -Version $env:NUnitConsoleVersion -OutputDirectory tools
      
      if ($env:IsFullIntegrationBuild -eq $true)
      {
          nuget install OpenCover -Version $env:OpenCoverVersion -OutputDirectory tools
          dotnet tool install --tool-path tools --version $env:CoverallsVersion coveralls.net
      }

test_script:
# Test & generate coverage report
  - ps: >-
      $nunitFolder = (Resolve-Path "tools\NUnit.ConsoleRunner.*\tools").ToString();
      $nunitConsole = (Resolve-Path "$nunitFolder\nunit3-console.exe").ToString();
      
      # Only take test assemblies matching their folder name
      # Example:
      # Directory = tests\TestProject.Tests\bin\CONFIGURATION\TARGET
      # Directory.Parent = tests\TestProject.Tests\bin\CONFIGURATION
      # Directory.Parent.Parent = tests\TestProject.Tests\bin
      # Directory.Parent.Parent.Parent = tests\TestProject.Tests
      
      $testAssemblies = (ls tests\*.Tests\bin\$env:Configuration\*\*Tests.dll | Where-Object { $_ -Match "net*" -and $_ -NotMatch "netcoreapp*" -and [System.IO.Path]::GetFileNameWithoutExtension($_.FullName) -Match $_.Directory.Parent.Parent.Parent.Name } | % FullName | sort-object -Unique)
      
      if ($env:IsFullIntegrationBuild -eq $true)
      {
          $opencover = (Resolve-Path "tools\OpenCover.*\tools\OpenCover.Console.exe").ToString();
          $coveralls = (Resolve-Path "tools\csmacnz.Coveralls.exe").ToString();
          
          & $opencover -register:Path64 -filter:"+[*]* -[*.Test*]* -[*]JetBrains.Annotations*" -target:"$nunitConsole" -targetargs:"$testAssemblies --result=\`"TestResult.xml\`"" -returntargetcode -log:Warn -output:coverage.xml
          
          & $sonarScanner end /d:"sonar.login=$env:SONARQUBE_TOKEN"
          
          & $coveralls --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
      }
      else
      {
          & $nunitConsole $testAssemblies
      }
      
      # Upload results to AppVeyor
      
      $wc = New-Object 'System.Net.WebClient';
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml));

# Artifacts
artifacts:
  - path: '**\bin\Release\*.nupkg'
    name: NuGet
  - path: '**\bin\Release\*.snupkg'
    name: NuGet symbols

# Documentation
before_deploy:
# Release documentation
  - ps: ./build/releaseDoc.ps1

# Deploy
deploy:
# MyGet
  - provider: NuGet
    server: https://www.myget.org/F/kernelith-ci/api/v2/package
    symbol_server: https://www.myget.org/F/kernelith-ci/symbols/api/v2/package
    api_key:
      secure: ANF+joC2B+NahxCFbLPOjNvEAo36F2F4QJu6zLwoIf2I9KwkxKyCSuNxDpLmJmtU
    on:
      configuration: Release
# GitHub packages
  - provider: NuGet
    server: https://nuget.pkg.github.com/KeRNeLith/index.json
    username: KeRNeLith
    api_key:
      secure: 6N37NtnuKSzKQXlPOCtPSFJGOvJUdJjPK8LcuWx2PjHs2WVdngenZvYixk6br72b
    skip_symbols: true
    artifact: NuGet
    on:
      configuration: Release
      APPVEYOR_REPO_TAG: true
# NuGet
  - provider: NuGet
    api_key:
      secure: a/0jxqKB5mP/ED1AIQ6YxAoiYZP93M5NQpyZbq40Tkzg+ye0MhFHlDQFBUefrseY
    on:
      configuration: Release
      APPVEYOR_REPO_TAG: true
# GitHub
  - provider: GitHub
    auth_token:
      secure: fLTTmcGOM55kigJC4vErpObFmybCtzQtwb4QN55BTNq3GDGaOCoHDoIPxexzO59d
    release: '${APPVEYOR_REPO_TAG_NAME}'
    description: 'Version ${Release_Name}'
    draft: false
    prerelease: false
    force_update: true
    on:
      configuration: Release
      APPVEYOR_REPO_TAG: true